### ISSUE TITLE
useful css snippets

### ISSUE THREAD

**Issue by bison1994** [bison1994/treasure#5]
```css
.element {
  position: sticky;
  top: 50px;
}
```

**Comment by bison1994** [comment]
```css
html {
  scroll-behavior: smooth;
}
```
